In [2]:
import numpy as np
# https://www.numpy.org

In [3]:
#配列の構築
print(np.array([1, 4, 2, 5, 3]))
print(np.array([range(i, i+3) for i in [2, 4, 6]]))
#numpyの特殊関数(ほんの一部)
print(np.zeros(10, dtype=int))
print(np.ones((2, 3), dtype=float))
print(np.arange(1, 10).reshape((3, 3)))

[1 4 2 5 3]
[[2 3 4]
 [4 5 6]
 [6 7 8]]
[0 0 0 0 0 0 0 0 0 0]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
#インデクス操作
#要素のアクセス
x1 = np.random.randint(10, size=6)
print(x1)
print(x1[1])
print(x1[-1])

x2 = np.random.randint(10, size=(3, 4))
print(x2)
print(x2[1, 2])

[0 5 8 8 5 7]
5
7
[[9 8 5 2]
 [3 4 8 9]
 [2 4 7 4]]
8


In [5]:
#スライス
x1 = np.random.randint(10, size=10)
print(x1)
print(x1[:5])
print(x1[5:])
print(x1[1::2])
print(x1[::-1])
print()
x2 = np.random.randint(10, size=(3, 4))
print(x2)
print(x2[:2, :3])
print(x2[:3, ::2])
print(x2[:, 0])
print(x2[0, :])

[9 6 5 6 2 5 8 6 8 7]
[9 6 5 6 2]
[5 8 6 8 7]
[6 6 5 6 7]
[7 8 6 8 5 2 6 5 6 9]

[[3 5 3 2]
 [2 3 1 4]
 [1 3 4 1]]
[[3 5 3]
 [2 3 1]]
[[3 3]
 [2 1]
 [1 4]]
[3 2 1]
[3 5 3 2]


In [6]:
#形状変更
print(np.arange(1, 10).reshape((3, 3)))
print()
x = np.array([1, 2, 3])
print(x[np.newaxis, :])
print(x[:, np.newaxis])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]]
[[1]
 [2]
 [3]]


In [7]:
#分割結合
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(np.vstack([x, y]))
print(np.hstack([x, y]))
print()

z = np.arange(16).reshape((4, 4))

upper, lower = np.vsplit(z, [2])
print(upper)
print(lower)

print()

left, right = np.hsplit(z, [2])
print(left)
print(right)


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [8]:
#配列の演算、変換
x = np.random.randint(1, 10, (3, 3))
print(np.add(x, 2))
# np.subtract
# np.multiply(x, 10, out=y)
# np.divide
# np.floor_divide
# np.power
# np.mod
# np.abs
# np.sin  arcsin
# np.cos  arccos
# np.tan  arctan
# np.exp
# np.log

#その他の演算
x = np.arange(1, 6)

print(np.add.reduce(x))
print(np.add.accumulate(x))
print(np.multiply.outer(x, x))

[[ 3  8  8]
 [ 6  6  6]
 [10  5  7]]
15
[ 1  3  6 10 15]
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


In [9]:
#配列の集約
x = np.arange(16).reshape((4, 4))

print(np.max(x))
print(np.min(x))
print(np.sum(x))

print(x.max(axis=0))
print(x.max(axis=1))

# np.prod 積
# np.mean 平均値
# np.std 標準偏差
# np.var 分散
# np.median 中央値
# np.percentile パーセンタイル

# np.sum(x < 6) 条件付きカウント　& | ~ ^ が使える
# x[x < 5] マスキング操作
# np.sort, np.argsort, np.partition

15
0
120
[12 13 14 15]
[ 3  7 11 15]


In [10]:
#行列
a = np.random.randint(0, 10, (3, 3))
b = np.random.randint(0, 10, (3, 3))
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a@b)
print(a.T)
print(np.linalg.det(a))
print(np.linalg.inv(a))

[[3 1 4]
 [5 4 8]
 [3 7 5]]
[[4 8 5]
 [6 6 2]
 [6 9 1]]
[[ 7  9  9]
 [11 10 10]
 [ 9 16  6]]
[[-1 -7 -1]
 [-1 -2  6]
 [-3 -2  4]]
[[12  8 20]
 [30 24 16]
 [18 63  5]]
[[ 42  66  21]
 [ 92 136  41]
 [ 84 111  34]]
[[3 5 3]
 [1 4 7]
 [4 8 5]]
-17.000000000000025
[[ 2.11764706 -1.35294118  0.47058824]
 [ 0.05882353 -0.17647059  0.23529412]
 [-1.35294118  1.05882353 -0.41176471]]


In [ ]:
# ブロードキャスト
# ファンシーインデックス
# 構造化配列

In [ ]:
import scipy
# https://www.scipy.org