In [1]:
import numpy as np
import scipy as sc
# https://www.numpy.org
# https://www.scipy.org

In [2]:
#配列の構築
print(np.array([1, 4, 2, 5, 3]))
print(np.array([range(i, i+3) for i in [2, 4, 6]]))
#numpyの特殊関数(ほんの一部)
print(np.zeros(10, dtype=int))
print(np.ones((2, 3), dtype=float))
print(np.arange(1, 10).reshape((3, 3)))

[1 4 2 5 3]
[[2 3 4]
 [4 5 6]
 [6 7 8]]
[0 0 0 0 0 0 0 0 0 0]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
#行列
a = np.random.randint(0, 10, (3, 3))
b = np.random.randint(0, 10, (3, 3))
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a@b)
print(a.T)
print(np.linalg.det(a))
print(np.linalg.inv(a))

[[8 5 0]
 [3 5 0]
 [9 9 2]]
[[1 6 3]
 [7 6 7]
 [3 2 1]]
[[ 9 11  3]
 [10 11  7]
 [12 11  3]]
[[ 7 -1 -3]
 [-4 -1 -7]
 [ 6  7  1]]
[[ 8 30  0]
 [21 30  0]
 [27 18  2]]
[[ 43  78  59]
 [ 38  48  44]
 [ 78 112  92]]
[[8 3 9]
 [5 5 9]
 [0 0 2]]
49.99999999999999
[[ 0.2  -0.2   0.  ]
 [-0.12  0.32 -0.  ]
 [-0.36 -0.54  0.5 ]]


In [3]:
#インデクス操作
#要素のアクセス
x1 = np.random.randint(10, size=6)
print(x1)
print(x1[1])
print(x1[-1])

x2 = np.random.randint(10, size=(3, 4))
print(x2)
print(x2[1, 2])

[8 5 3 6 1 4]
5
4
[[2 3 3 8]
 [3 9 2 1]
 [6 5 5 4]]
2


In [4]:
#スライス
x1 = np.random.randint(10, size=10)
print(x1)
print(x1[:5])
print(x1[5:])
print(x1[1::2])
print(x1[::-1])

x2 = np.random.randint(10, size=(3, 4))
print(x2)
print(x2[:2, :3])
print(x2[:3, ::2])
print(x2[:, 0])
print(x2[0, :])

[1 2 5 3 9 6 8 8 7 1]
[1 2 5 3 9]
[6 8 8 7 1]
[2 3 6 8 1]
[1 7 8 8 6 9 3 5 2 1]
[[8 4 0 9]
 [3 5 6 5]
 [9 0 5 2]]
[[8 4 0]
 [3 5 6]]
[[8 0]
 [3 6]
 [9 5]]
[8 3 9]
[8 4 0 9]


In [5]:
#形状変更
print(np.arange(1, 10).reshape((3, 3)))

x = np.array([1, 2, 3])
print(x[np.newaxis, :])
print(x[:, np.newaxis])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]]
[[1]
 [2]
 [3]]


In [7]:
#分割結合
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(np.vstack([x, y]))
print(np.hstack([x, y]))

z = np.arange(16).reshape((4, 4))

upper, lower = np.vsplit(z, [2])
print(upper)
print(lower)

left, right = np.hsplit(z, [2])
print(left)
print(right)


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [8]:
#配列の演算、変換
x = np.random.randint(1, 10, (3, 3))
print(np.add(x, 2))
# np.subtract
# np.multiply(x, 10, out=y)
# np.divide
# np.floor_divide
# np.power
# np.mod
# np.abs
# np.sin  arcsin
# np.cos  arccos
# np.tan  arctan
# np.exp
# np.log

[[5 8 4]
 [4 8 7]
 [9 6 9]]


In [ ]:
#上記の続き
x = np.arange(1, 6)

print(np.add.reduce(x))
print(np.add.accumulate(x))
print(np.multiply.outer(x, x))


In [9]:
#配列の集約
x = np.arange(16).reshape((4, 4))

print(np.max(x))
print(np.min(x))
print(np.sum(x))

print(x.max(axis=0))
print(x.max(axis=1))

# np.prod 積
# np.mean 平均値
# np.std 標準偏差
# np.var 分散
# np.median 中央値
# np.percentile パーセンタイル

# np.sum(x < 6) 条件付きカウント　& | ~ ^ が使える
# x[x < 5] マスキング操作
# np.sort, np.argsort, np.partition

15
0
120
[12 13 14 15]
[ 3  7 11 15]


In [ ]:
from scipy import special
# https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.gamma.html

In [10]:
#そのほかの知識
# ブロードキャスト
# ファンシーインデックス
# 構造化配列